### ISSUE TITLE
Running on windows does nothing at all

### ISSUE THREAD

**Issue by emberdart** [kraenhansen/dotenv-run-script#10]
I just get "Done in..." with nothing being run - when I try to run in windows - but haven't seen any recommendations about a workaround. Is it not supported or should it be working? Thanks

**Comment by kraenhansen** [comment]
It should work. What versions are you using and what do you put in your script? Are you using WSL?

**Comment by kraenhansen** [comment]
Feel free to reopen, providing the details above 👍
