### ISSUE TITLE
Need `shell: true` option on Windows

### ISSUE THREAD

**Issue by floyd-may** [kraenhansen/dotenv-run-script#5]
dotenv-run-script doesn't work on windows since the `npm` executable is actually `npm.cmd`, which requires a shell to execute. Editing the `spawnSync` call to add the `shell: true` option solves the problem for me.

([relevant docs](https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows))

**Comment by kraenhansen** [comment]
I don't have access to a windows machine myself, but I'll set up a quick test on GitHub Actions when time allows 👍

Also  - although admittedly a small fix, PRs are welcome 😁

**Comment by floyd-may** [comment]
> Also - although admittedly a small fix, PRs are welcome 😁

Understood 😅 I figured a thorough description of my hacky workaround would probably be a more efficient way to enable someone making a PR than me fumbling my way through the PR process in a brand new repo. If it were more urgent I'd probably have made a PR. Thanks for taking a look!
