### ISSUE TITLE
How to parse special characters?

### ISSUE THREAD

**Issue by rogeraraujo90** [kraenhansen/dotenv-run-script#6]
When there are special characters in the env var they are not parsed.

Ex: My env var: DATABASE_PASSWORD=123$$6

If I run my script with dotenv-run-script and console log the var the result is:

```js
console.log("Value is:", process.env.DATABASE_PASSWORD);
```

```shell
Value is 123
```

**Comment by kraenhansen** [comment]
This is most likely a consequence of the expand feature (the package use [dotenv-expand](https://www.npmjs.com/package/dotenv-expand) to achieve this). Is it possible for you to simply escape the `$` and use `\$` instead?
